name: Docker Image Publish

on:
  push:
    branches: [ "main" ]

jobs:

  publish:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata for jinaga-replicator
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: jinaga/jinaga-replicator

    - name: Publish the jinaga-replicator image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          jinaga/jinaga-replicator:$(date +%s)
          jinaga/jinaga-replicator:latest

  
